[2023-06-29 09:57:23,795] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-16T14:01:57+00:00 [queued]>
[2023-06-29 09:57:23,897] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-16T14:01:57+00:00 [queued]>
[2023-06-29 09:57:23,898] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 09:57:23,899] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-06-29 09:57:23,900] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 09:57:23,975] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): create_user> on 2023-06-16T14:01:57+00:00
[2023-06-29 09:57:23,980] {standard_task_runner.py:52} INFO - Started process 34982 to run task
[2023-06-29 09:57:23,992] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_user', '2023-06-16T14:01:57+00:00', '--job-id', '5271', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/test.py', '--cfg-path', '/tmp/tmpf7owr5md', '--error-file', '/tmp/tmp7p3rgooo']
[2023-06-29 09:57:23,994] {standard_task_runner.py:77} INFO - Job 5271: Subtask create_user
[2023-06-29 09:57:24,098] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.create_user 2023-06-16T14:01:57+00:00 [running]> on host d9c3ec86c3ab
[2023-06-29 09:57:24,438] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2023-06-16T14:01:57+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-16T14:01:57+00:00
[2023-06-29 09:57:24,441] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-06-29 09:57:24,442] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nid -u test_user;\nif [$? -eq o];\n    then echo "User exists"\nelse sudo useradd -r test_user;\n    echo "User created";\nfi']
[2023-06-29 09:57:24,455] {subprocess.py:75} INFO - Output:
[2023-06-29 09:57:24,530] {subprocess.py:79} INFO - id: ‘test_user’: no such user
[2023-06-29 09:57:24,538] {subprocess.py:79} INFO - bash: line 2: [1: command not found
[2023-06-29 09:57:24,601] {subprocess.py:79} INFO - 
[2023-06-29 09:57:24,603] {subprocess.py:79} INFO - We trust you have received the usual lecture from the local System
[2023-06-29 09:57:24,604] {subprocess.py:79} INFO - Administrator. It usually boils down to these three things:
[2023-06-29 09:57:24,605] {subprocess.py:79} INFO - 
[2023-06-29 09:57:24,606] {subprocess.py:79} INFO -     #1) Respect the privacy of others.
[2023-06-29 09:57:24,606] {subprocess.py:79} INFO -     #2) Think before you type.
[2023-06-29 09:57:24,607] {subprocess.py:79} INFO -     #3) With great power comes great responsibility.
[2023-06-29 09:57:24,608] {subprocess.py:79} INFO - 
[2023-06-29 09:57:24,608] {subprocess.py:79} INFO - sudo: no tty present and no askpass program specified
[2023-06-29 09:57:24,614] {subprocess.py:79} INFO - User created
[2023-06-29 09:57:24,618] {subprocess.py:83} INFO - Command exited with return code 0
[2023-06-29 09:57:24,694] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_user, execution_date=20230616T140157, start_date=20230629T095723, end_date=20230629T095724
[2023-06-29 09:57:24,773] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-29 09:57:24,813] {local_task_job.py:151} INFO - Task exited with return code 0
