[2023-07-30 11:46:36,758] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-22T14:01:12+00:00 [queued]>
[2023-07-30 11:46:36,928] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-22T14:01:12+00:00 [queued]>
[2023-07-30 11:46:36,929] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-30 11:46:36,930] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-07-30 11:46:36,930] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-30 11:46:36,985] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): create_user> on 2023-06-22T14:01:12+00:00
[2023-07-30 11:46:36,990] {standard_task_runner.py:52} INFO - Started process 1688 to run task
[2023-07-30 11:46:37,003] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_user', '2023-06-22T14:01:12+00:00', '--job-id', '13955', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/test.py', '--cfg-path', '/tmp/tmpbr26vbi1', '--error-file', '/tmp/tmpqop30it7']
[2023-07-30 11:46:37,005] {standard_task_runner.py:77} INFO - Job 13955: Subtask create_user
[2023-07-30 11:46:37,110] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.create_user 2023-06-22T14:01:12+00:00 [running]> on host fd6918d9d7f3
[2023-07-30 11:46:37,586] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2023-06-22T14:01:12+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-22T14:01:12+00:00
[2023-07-30 11:46:37,589] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-07-30 11:46:37,591] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nid -u test_user;\nif [$? -eq o];\n    then echo "User exists"\nelse sudo useradd -r test_user;\n    echo "User created";\nfi']
[2023-07-30 11:46:37,603] {subprocess.py:75} INFO - Output:
[2023-07-30 11:46:37,678] {subprocess.py:79} INFO - id: ‘test_user’: no such user
[2023-07-30 11:46:37,685] {subprocess.py:79} INFO - bash: line 2: [1: command not found
[2023-07-30 11:46:37,761] {subprocess.py:79} INFO - 
[2023-07-30 11:46:37,762] {subprocess.py:79} INFO - We trust you have received the usual lecture from the local System
[2023-07-30 11:46:37,763] {subprocess.py:79} INFO - Administrator. It usually boils down to these three things:
[2023-07-30 11:46:37,764] {subprocess.py:79} INFO - 
[2023-07-30 11:46:37,765] {subprocess.py:79} INFO -     #1) Respect the privacy of others.
[2023-07-30 11:46:37,765] {subprocess.py:79} INFO -     #2) Think before you type.
[2023-07-30 11:46:37,766] {subprocess.py:79} INFO -     #3) With great power comes great responsibility.
[2023-07-30 11:46:37,767] {subprocess.py:79} INFO - 
[2023-07-30 11:46:37,767] {subprocess.py:79} INFO - sudo: no tty present and no askpass program specified
[2023-07-30 11:46:37,777] {subprocess.py:79} INFO - User created
[2023-07-30 11:46:37,780] {subprocess.py:83} INFO - Command exited with return code 0
[2023-07-30 11:46:37,839] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_user, execution_date=20230622T140112, start_date=20230730T114636, end_date=20230730T114637
[2023-07-30 11:46:37,918] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-30 11:46:37,939] {local_task_job.py:151} INFO - Task exited with return code 0
